spring:
  application:
    name: afang-user

server:
  port: 8123
  servlet:
    context-path: /api

# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn

# Swagger configuration
springfox:
  documentation:
    swagger-ui:
      enabled: true


# Tencent Cloud COS Configuration (optional)
# cos:
#   client:
#     host: your-cos-host
#     secretId: your-secret-id
#     secretKey: your-secret-key
#     region: your-region
#     bucket: your-bucket
