spring:
  application:
    name: afang-user-backend

  datasource:
    url: jdbc:mysql://localhost:3306/afang?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: Mysql123456
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8123
  servlet:
    context-path: /api

#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#        format_sql: true
#        connection:
#          charset: utf8mb4
#          unicode: true
#    database: mysql